// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Context;

namespace Models.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20211110104739_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Context.Users", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UUID");

                    b.Property<string>("administrationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("administrationName");

                    b.Property<string>("administrationOId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("administrationOId");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateCreated");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateDeleted");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateUpdated");

                    b.Property<string>("employeeIdentifier")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employeeIdentifier");

                    b.Property<string>("employeeNames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employeeNames");

                    b.Property<string>("employeePosition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("employeePosition");

                    b.Property<Guid>("identityID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("identityID");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("lawReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lawReason");

                    b.Property<string>("processorID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("processorID");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remark");

                    b.Property<string>("serviceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serviceType");

                    b.Property<string>("serviceURI")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serviceURI");

                    b.HasKey("UUID");

                    b.ToTable("Users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
